# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [ 
	{   
		:name => "hello-servicemesh-envoy"
	}   
]

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  config.vm.box = "ubuntu/xenial64" # 16.04 LTS
  config.vm.hostname = "hello-servicemesh-envoy"
  # config.vm.provision "docker" # Just install it
  config.vm.network "private_network", ip: "10.10.10.150"
  config.vm.provision :shell, path: "bin/bootstrap.sh"
  config.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/hello-servicemesh-envoy.yml"
  config.ssh.forward_agent = true

  # Increase memory for Parallels Desktop
  config.vm.provider "parallels" do |p, o|
    p.memory = "8192"
  end

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 4
  end

  # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "8192"
    end
  end
end
